//car listing data for a vehicle inventory system
const vehicleDatabase = [
    {
        id: 'hyundai-i20-2016',
        title: 'Hyundai I20 Coupe',
        year: 2016,
        price: '£5000',
        mileage: 70500,
        fuelType: 'Petrol',
        transmission: 'Manual',
        engineSize: '1.2L',
        status: 'available',
        images: [
            'cars/hyundai/main.jpg',
            'cars/hyundai/main2.jpg',
            'cars/hyundai/front.jpg',
            'cars/hyundai/main3.jpg',
            'cars/hyundai/main4.jpg',
            'cars/hyundai/back1.jpg',
            'cars/hyundai/back2.jpg',
            'cars/hyundai/back.jpg',
            'cars/hyundai/back3.jpg',
            'cars/hyundai/back4.jpg',
            'cars/hyundai/boot.jpg',
            'cars/hyundai/dash.jpg',
            'cars/hyundai/dash2.jpg',
            'cars/hyundai/dash3.jpg',
            'cars/hyundai/steering.jpg',
            'cars/hyundai/frontseats.jpg',
            'cars/hyundai/backseats.jpg',
            'cars/hyundai/cupholder.jpg',

        ],
        description: `Hyundai I20 Coupe 1.2 Petrol in good condition.  The car comes with MOT until November 2026, Service History, a Fresh Service and had a New Clutch. I have the invoice for the work that’s been carried out. The car drives well and comes with some nice features which include Central Locking, Electric Windows, Electric Mirrors, AM/FM Stereo with Bluetooth Connectivity, Cruise Control, Hands Free and Rear Parking Sensors.`
    }, 
    {
        id: 'nissan-xtrail-2016',
        title: 'Nissan X-Trail Acenta',
        year: 2016,
        price: '£7500',
        mileage: 57000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        engineSize: '1.6L',
        status: 'available',
        images: [
            'cars/nissanxtrail/main.webp',
            'cars/nissanxtrail/left.webp',
            'cars/nissanxtrail/backright2.webp',
            'cars/nissanxtrail/backleft3.webp',
            'cars/nissanxtrail/Front.webp',
            'cars/nissanxtrail/back.webp',
            'cars/nissanxtrail/boot.webp',
            'cars/nissanxtrail/left2.webp',    
            'cars/nissanxtrail/side.webp',           
            'cars/nissanxtrail/backleft.webp',    
            'cars/nissanxtrail/backleft2.webp',  
            'cars/nissanxtrail/backright.webp',   
            'cars/nissanxtrail/roof.webp',   
            'cars/nissanxtrail/roofopen.webp',   
            'cars/nissanxtrail/dash.webp',  
            'cars/nissanxtrail/frontseats2.webp',  
            'cars/nissanxtrail/frontseats.webp',
            'cars/nissanxtrail/radio.webp',
            'cars/nissanxtrail/backseats.webp',
            'cars/nissanxtrail/backseats2.webp',  
            'cars/nissanxtrail/wheel1.webp',   
            'cars/nissanxtrail/wheel2.webp',   
            'cars/nissanxtrail/wheel3.webp',
            'cars/nissanxtrail/wheel4.webp'
        ],
        description: `Stunning Nissan X-Trail 2016 Acenta in very good condition. The car comes with Full Service History, MOT until June 2026 and 2 Keys. It's just had a fresh service. The car drives perfectly with no unwanted noises. It comes with some nice features aswell which includes Central Locking, Electric Windows, Electric Mirrors, Electric Folding Mirrors, AM/FM Stereo with Bluetooth Connectivity, Duel Climate Control, Air Conditioning, Multi-Functioning Steering Wheel, Cruise Control, Sunroof, Front and Rear Parking Sensors.`
    },

    // Sold Vehicles section
    {
     id: 'honda-crv-2013',
        title: 'Honda CR-V i-DTEC SE',
        year: 2013,
        status: 'sold',
        images: [
            'cars/soldcars/HondaCRVRED.jpg',
        ]
    },
    {
     id: 'ford-kuga-2014',
        title: 'Ford Kuga Titanium AWD Euro 5',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fordkugablue.jpg' ],
    },
    {
    id: 'nissan-qashqai-2016',
        title: 'Nissan Qashqai DIG-T N-Connecta Euro 6',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqasgrey.jpg' ],
    },
    {
     id: 'ford-tranzitConnect-2017',
        title: 'Ford Transit Connect',
        year: 2017,
        status: 'sold',
         images: [ 'cars/soldcars/fordTanzitWhite.jpg' ],
    },
        {
    id: 'citroen-c4-picaso-2015',
        title: 'Citroen Grand C4 Picasso',
        year: 2015,
        status: 'sold',
        images: [
            'cars/soldcars/picaso.jpg'],
    },
           {
        id: 'Seat-Ibiza-2016',
        title: 'Seat Ibiza Vista Sport',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/ibiza.webp' ],
    }, 
       {
        id: 'Peugeot-2008-2017',
        title: 'Peugeot 2008 Active',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/2008.jpg' ],
    }, 
    {
        id: 'ford-fiesta-2014',
        title: 'Ford Fiesta Zetec',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fiestablue.webp' ],
    },
    {
        id: 'peugeot-2008-2017',
        title: 'Peugeot 2008 Allure',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/peugot.webp' ],
    },
    {
        id: 'vauxhall-vivaro-2020',
        title: 'Vauxhall Vivaro 2700 Dynamic S/S',
        year: 2020,
        status: 'sold',
        images: [ 'cars/soldcars/vivaro.webp' ],
    },
    {
        id: 'audi-a1-2013',
        title: 'Audi A1 Sport',
        year: 2013,
        status: 'sold',
        images: [ 'cars/soldcars/audiA1.webp' ],
    },
    {
        id: 'ford-transit-connect-2019',
        title: 'Ford Transit Connect',
        year: 2019,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransit.webp' ],
    },
    {
        id: 'honda-crv-2015',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondaCRV.webp' ],
    },
    {
        id: 'ford-transit-custom-2016-blue',
        title: 'Ford Transit Custom 290',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransitblue.webp' ],
    },
    {
        id: 'ford-focus-2017',
        title: 'Ford Focus Zetec Ecoboost',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/fordfocus.jpg' ],
    },
   {
        id: 'bmw-x1-2014',
        title: 'BMW X1 SE',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/bmwx1.jpg' ],
    },
    {
        id: 'ford-fiesta-2011',
        title: 'Ford Fiesta Titanium',
        year: 2011,
        status: 'sold',
        images: [ 'cars/soldcars/blackfiesta.jpg' ],
    },
    {
        id: 'honda-crv-2015-grey',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondacrvgrey.webp' ],
    },
    {
        id: 'nissan-qashqai-2014',
        title: 'Nissan Qashqai',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqas.webp' ],
    },
];

const featuredVehicleIds = ['nissan-xtrail-2016','hyundai-i20-2016'];