//car listing data for a vehicle inventory system
const vehicleDatabase = [
     {
        id: 'kia-ceed-2020',
        title: 'Kia Ceed GDi ECO 2 Sportswagon Euro 6',
        year: 2020,
        price: '£9000',
        mileage: 61351,
        fuelType: 'Petrol',
        transmission: 'Manual',
        engineSize: '1.0L',
        status: 'available',
        images: [
            'cars/Kia/main1.jpg',
            'cars/Kia/main2.jpg',
            'cars/Kia/front.jpg',
            'cars/Kia/main3.jpg',
            'cars/Kia/main4.jpg',
            'cars/Kia/back1.jpg',
            'cars/Kia/back2.jpg',
            'cars/Kia/back.jpg',
            'cars/Kia/back3.jpg',
            'cars/Kia/back4.jpg',
            'cars/Kia/boot.jpg',
            'cars/Kia/forntseats.jpg',
            'cars/Kia/frontseats1.jpg',
            'cars/Kia/frontseats2.jpg',
            'cars/Kia/frontseats3.jpg',
            'cars/Kia/backseats.jpg',
            'cars/Kia/backseats1.jpg',
            'cars/Kia/backseats2.jpg',
            'cars/Kia/dash.jpg',
            'cars/Kia/dash1.jpg',
            'cars/Kia/console.jpg',
            'cars/Kia/console1.jpg',
            'cars/Kia/console2.jpg',           
        ],
        description: `This Kia Ceed Sportswagon is a fantastic choice if you need the practicality of an estate without the high running costs. The 1.0L Turbo engine (6-speed) strikes a great balance—it is punchy enough for the motorway but keeps fuel and insurance costs down.
         The car drives perfectly and it comes with service history and a fresh service. This car comes with some nice features which include Central Locking, Electric Windows,  AM/FM Stereo with Bluetooth Connectivity, Automatic Lights, Multi-Functioning Steering Wheel, Cruise Control and Revising Camera.`
    },

    {
        id: 'peugeot-2008-2016',
        title: 'Peugeot 2008 Allure',
        year: 2016,
        price: '£5500',
        mileage: 69500,
        fuelType: 'Diesel',
        transmission: 'Manual',
        engineSize: '1.6L',
        status: 'available',
        images: [
            'cars/2008/main.jpg',
            'cars/2008/main2.jpg',
            'cars/2008/front.jpg',
            'cars/2008/main3.jpg',
            'cars/2008/main4.jpg',
            'cars/2008/back1.jpg',
            'cars/2008/back2.jpg',
            'cars/2008/back.jpg',
            'cars/2008/back3.jpg',
            'cars/2008/boot.jpg',
            'cars/2008/frontseats.jpg',
            'cars/2008/frontseats2.jpg',
            'cars/2008/frontseats3.jpg',
            'cars/2008/backseats.jpg',
            'cars/2008/backseats2.jpg',
            'cars/2008/dash.jpg',
            'cars/2008/dash1.jpg',
            'cars/2008/dash2.jpg',
            'cars/2008/radio.jpg',
            'cars/2008/radio2.jpg',           
        ],
        description: `Peugeot 2008 1.6 Diesel in very good condition. The car has only done 69500 Miles, comes with 2 Keys, Full-Service History and MOT until September 2026. Its recently had some work done to it which includes a New Timing Belt Kit with Water pump, Disc and Pads all around as well. I have the invoices of all the work that's been carries out. The car drives perfectly and it comes with some nice features as well which includes Central Locking, Electric Windows, Electric Mirrors, Electric Folding Mirrors, Dual Climate Control, AM/FM Stereo with Bluetooth Connectivity, Apple CarPlay, Air Conditioning, Cruise Control and Rear Parking Sensors.`
    },

       {
        id: 'nissan-xtrail-2016',
        title: 'Nissan X-Trail Acenta',
        year: 2016,
        price: '£7500',
        mileage: 58000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        engineSize: '1.6L',
        status: 'available',
        images: [
            'cars/nissanxtrail/main.webp',
            'cars/nissanxtrail/left.webp',
            'cars/nissanxtrail/backright2.webp',
            'cars/nissanxtrail/backleft3.webp',
            'cars/nissanxtrail/Front.webp',
            'cars/nissanxtrail/back.webp',
            'cars/nissanxtrail/boot.webp',
            'cars/nissanxtrail/left2.webp',    
            'cars/nissanxtrail/side.webp',           
            'cars/nissanxtrail/backleft.webp',    
            'cars/nissanxtrail/backleft2.webp',  
            'cars/nissanxtrail/backright.webp',   
            'cars/nissanxtrail/roof.webp',   
            'cars/nissanxtrail/roofopen.webp',   
            'cars/nissanxtrail/dash.webp',  
            'cars/nissanxtrail/frontseats2.webp',  
            'cars/nissanxtrail/frontseats.webp',
            'cars/nissanxtrail/radio.webp',
            'cars/nissanxtrail/backseats.webp',
            'cars/nissanxtrail/backseats2.webp',  
            'cars/nissanxtrail/wheel1.webp',   
            'cars/nissanxtrail/wheel2.webp',   
            'cars/nissanxtrail/wheel3.webp',
            'cars/nissanxtrail/wheel4.webp'
        ],
        description: `Stunning Nissan X-Trail 2016 Acenta in very good condition. The car comes with Full Service History, MOT until June 2026 and 2 Keys. It's just had a fresh service. The car drives perfectly with no unwanted noises. It comes with some nice features aswell which includes Central Locking, Electric Windows, Electric Mirrors, Electric Folding Mirrors, AM/FM Stereo with Bluetooth Connectivity, Duel Climate Control, Air Conditioning, Multi-Functioning Steering Wheel, Cruise Control, Sunroof, Front and Rear Parking Sensors.`
    },

    // Sold Vehicles section
    {
     id: 'honda-crv-2013',
        title: 'Honda CR-V i-DTEC SE',
        year: 2013,
        status: 'sold',
        images: [
            'cars/soldcars/HondaCRVRED.jpg',
        ]
    },
    {
     id: 'ford-kuga-2014',
        title: 'Ford Kuga Titanium AWD Euro 5',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fordkugablue.jpg' ],
    },
    {
    id: 'nissan-qashqai-2016',
        title: 'Nissan Qashqai DIG-T N-Connecta Euro 6',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqasgrey.jpg' ],
    },
    {
     id: 'ford-tranzitConnect-2017',
        title: 'Ford Transit Connect',
        year: 2017,
        status: 'sold',
         images: [ 'cars/soldcars/fordTanzitWhite.jpg' ],
    },
        {
    id: 'citroen-c4-picaso-2015',
        title: 'Citroen Grand C4 Picasso',
        year: 2015,
        status: 'sold',
        images: [
            'cars/soldcars/picaso.jpg'],
    },
           {
        id: 'Seat-Ibiza-2016',
        title: 'Seat Ibiza Vista Sport',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/ibiza.webp' ],
    }, 
       {
        id: 'Peugeot-2008-2017',
        title: 'Peugeot 2008 Active',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/2008.jpg' ],
    }, 
    {
        id: 'ford-fiesta-2014',
        title: 'Ford Fiesta Zetec',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fiestablue.webp' ],
    },
    {
        id: 'peugeot-2008-2017',
        title: 'Peugeot 2008 Allure',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/peugot.webp' ],
    },
    {
        id: 'vauxhall-vivaro-2020',
        title: 'Vauxhall Vivaro 2700 Dynamic S/S',
        year: 2020,
        status: 'sold',
        images: [ 'cars/soldcars/vivaro.webp' ],
    },
    {
        id: 'audi-a1-2013',
        title: 'Audi A1 Sport',
        year: 2013,
        status: 'sold',
        images: [ 'cars/soldcars/audiA1.webp' ],
    },
    {
        id: 'ford-transit-connect-2019',
        title: 'Ford Transit Connect',
        year: 2019,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransit.webp' ],
    },
    {
        id: 'honda-crv-2015',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondaCRV.webp' ],
    },
    {
        id: 'ford-transit-custom-2016-blue',
        title: 'Ford Transit Custom 290',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransitblue.webp' ],
    },
    {
        id: 'ford-focus-2017',
        title: 'Ford Focus Zetec Ecoboost',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/fordfocus.jpg' ],
    },
   {
        id: 'bmw-x1-2014',
        title: 'BMW X1 SE',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/bmwx1.jpg' ],
    },
    {
        id: 'ford-fiesta-2011',
        title: 'Ford Fiesta Titanium',
        year: 2011,
        status: 'sold',
        images: [ 'cars/soldcars/blackfiesta.jpg' ],
    },
    {
        id: 'honda-crv-2015-grey',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondacrvgrey.webp' ],
    },
    {
        id: 'nissan-qashqai-2014',
        title: 'Nissan Qashqai',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqas.webp' ],
    },
];
const featuredVehicleIds = ['nissan-xtrail-2016','peugeot-2008-2016','kia-ceed-2020'];