//car listing data for a vehicle inventory system
const vehicleDatabase = [
    {
        id: 'ford-ka-2019',
        title: 'Ford KA+ Active',
        year: 2019,
        price: '£7000',
        mileage: 36000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        engineSize: '1.2L',
        status: 'available',
        images: [
            'cars/fordka/main.jpeg',
            'cars/fordka/main2.jpeg',
            'cars/fordka/front.jpeg',
            'cars/fordka/main3.jpeg',
            'cars/fordka/main4.jpeg',
            'cars/fordka/back1.jpeg',
            'cars/fordka/back2.jpeg',
            'cars/fordka/back.jpeg',
            'cars/fordka/back3.jpeg',
            'cars/fordka/back4.jpeg',
            'cars/fordka/boot.jpeg',
            'cars/fordka/frontseats.jpeg',
            'cars/fordka/frontseats1.jpeg',
            'cars/fordka/frontseats2.jpeg',
            'cars/fordka/frontseats3.jpeg',
            'cars/fordka/backseats.jpeg',
            'cars/fordka/backseats1.jpeg',
            'cars/fordka/sterring.jpeg',
            'cars/fordka/radio.jpeg',

        ],
        description: `If you are looking for a reliable, fuss-free runner, this KA+ Active is perfect. It has covered just 36,000 miles and is ready to drive away with zero headaches. I have just had the car serviced, and it comes with a long MOT until December 2026, so you won't need to worry about maintenance costs. It drives perfectly smooth, responsive, and ideal for both city driving and longer commutes. It also comes with some nice features which include Central Locking, Electric Windows, Electric Mirrors, Cruise Control, Air Conditioning and AM/FM Stereo with Bluetooth Connectivity. The car does have a few age-related marks but overall, it’s in good condition.`
    },
     {
        id: 'ford-kuga-2016',
        title: 'Ford Kuga Titanium Sport',
        year: 2016,
        price: '£7000',
        mileage: 77000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        engineSize: '2.0L',
        status: 'available',
        images: [
            'cars/fordkuga/main1.jpeg',
            'cars/fordkuga/main2.jpeg',
            'cars/fordkuga/front.jpeg',     
            'cars/fordkuga/main3.jpeg',
            'cars/fordkuga/main4.jpeg',
            'cars/fordkuga/back1.jpeg',
            'cars/fordkuga/back2.jpeg',
            'cars/fordkuga/back.jpeg',
            'cars/fordkuga/back3.jpeg',
            'cars/fordkuga/back4.jpeg',
            'cars/fordkuga/boot.jpeg',
            'cars/fordkuga/frontseats.jpeg',
            'cars/fordkuga/frontseats2.jpeg',
            'cars/fordkuga/backseats.jpeg',
            'cars/fordkuga/backseats2.jpeg',
            'cars/fordkuga/backseats3.jpeg',
            'cars/fordkuga/center console.jpeg',
            'cars/fordkuga/satnav.jpeg',
            'cars/fordkuga/screen.jpeg', 

        ],
        description: `This Ford Kuga Titanium Sport is a fantastic choice if you need a practical SUV with reliable performance. The 2.0L Diesel engine strikes a great balance—it is powerful for the motorway but smooth for daily driving. The car drives perfectly and has just had the timing belt, water pump, and brakes replaced (with invoices). These were replaced at 75817 on the clock. It comes with Full-Service History and MOT until Dec next year. It comes with some nice features as well such as Central Locking, Electric Windows, Electric Mirrors, Keyless Start, Automatic Headlights, Cruise Control, Air Conditioning, Self-Parking, Sat Nav, AM/FM Stereo with Bluetooth Connectivity, Front and Rear Parking Sensors.`
    },
     {
        id: 'kia-ceed-2020',
        title: 'Kia Ceed GDi ECO 2 Sportswagon Euro 6',
        year: 2020,
        price: '£9000',
        mileage: 61351,
        fuelType: 'Petrol',
        transmission: 'Manual',
        engineSize: '1.0L',
        status: 'available',
        images: [
            'cars/Kia/main1.jpg',
            'cars/Kia/main2.jpg',
            'cars/Kia/front.jpg',
            'cars/Kia/main3.jpg',
            'cars/Kia/main4.jpg',
            'cars/Kia/back1.jpg',
            'cars/Kia/back2.jpg',
            'cars/Kia/back.jpg',
            'cars/Kia/back3.jpg',
            'cars/Kia/back4.jpg',
            'cars/Kia/boot.jpg',
            'cars/Kia/forntseats.jpg',
            'cars/Kia/frontseats1.jpg',
            'cars/Kia/frontseats2.jpg',
            'cars/Kia/frontseats3.jpg',
            'cars/Kia/backseats.jpg',
            'cars/Kia/backseats1.jpg',
            'cars/Kia/backseats2.jpg',
            'cars/Kia/dash.jpg',
            'cars/Kia/dash1.jpg',
            'cars/Kia/console.jpg',
            'cars/Kia/console1.jpg',
            'cars/Kia/console2.jpg',           
        ],
        description: `This Kia Ceed Sportswagon is a fantastic choice if you need the practicality of an estate without the high running costs. The 1.0L Turbo engine (6-speed) strikes a great balance—it is punchy enough for the motorway but keeps fuel and insurance costs down.
         The car drives perfectly and it comes with service history and a fresh service. This car comes with some nice features which include Central Locking, Electric Windows,  AM/FM Stereo with Bluetooth Connectivity, Automatic Lights, Multi-Functioning Steering Wheel, Apple & Android CarPlay, Cruise Control and Revising Camera.`
    },

    

       {
        id: 'nissan-xtrail-2016',
        title: 'Nissan X-Trail Acenta',
        year: 2016,
        price: '£7500',
        mileage: 58000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        engineSize: '1.6L',
        status: 'available',
        images: [
            'cars/nissanxtrail/main.webp',
            'cars/nissanxtrail/left.webp',
            'cars/nissanxtrail/backright2.webp',
            'cars/nissanxtrail/backleft3.webp',
            'cars/nissanxtrail/Front.webp',
            'cars/nissanxtrail/back.webp',
            'cars/nissanxtrail/boot.webp',
            'cars/nissanxtrail/left2.webp',    
            'cars/nissanxtrail/side.webp',           
            'cars/nissanxtrail/backleft.webp',    
            'cars/nissanxtrail/backleft2.webp',  
            'cars/nissanxtrail/backright.webp',   
            'cars/nissanxtrail/roof.webp',   
            'cars/nissanxtrail/roofopen.webp',   
            'cars/nissanxtrail/dash.webp',  
            'cars/nissanxtrail/frontseats2.webp',  
            'cars/nissanxtrail/frontseats.webp',
            'cars/nissanxtrail/radio.webp',
            'cars/nissanxtrail/backseats.webp',
            'cars/nissanxtrail/backseats2.webp',  
            'cars/nissanxtrail/wheel1.webp',   
            'cars/nissanxtrail/wheel2.webp',   
            'cars/nissanxtrail/wheel3.webp',
            'cars/nissanxtrail/wheel4.webp'
        ],
        description: `This X-Trail Acenta is a low-mileage gem that feels fresh and has years of life left in it. The standout feature is the Panoramic Sunroof (check the photos), which floods the cabin with light and makes the whole car feel more premium. It’s practical, too, with Front and Rear Parking Sensors to help with the size, Dual Climate Control, and Cruise Control for motorway runs. We have just given it a fresh service to back up its Full Service History, and it comes with a long MOT until June 2026. A spacious, safe, and reliable family car that hasn't been overworked.` 
    },
    // Sold Vehicles section
    {
     id: 'honda-crv-2013',
        title: 'Honda CR-V i-DTEC SE',
        year: 2013,
        status: 'sold',
        images: [
            'cars/soldcars/HondaCRVRED.jpg',
        ]
    },
    {
        id: 'peugeot-2008-2016',
        title: 'Peugeot 2008 Allure',
       year: 2016,
        status: 'sold',
        images: [
            'cars/soldcars/Peugeot 2008.jpg'
            ],
    },
    {
     id: 'ford-kuga-2014',
        title: 'Ford Kuga Titanium AWD Euro 5',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fordkugablue.jpg' ],
    },
    {
    id: 'nissan-qashqai-2016',
        title: 'Nissan Qashqai DIG-T N-Connecta Euro 6',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqasgrey.jpg' ],
    },
    {
     id: 'ford-tranzitConnect-2017',
        title: 'Ford Transit Connect',
        year: 2017,
        status: 'sold',
         images: [ 'cars/soldcars/fordTanzitWhite.jpg' ],
    },
        {
    id: 'citroen-c4-picaso-2015',
        title: 'Citroen Grand C4 Picasso',
        year: 2015,
        status: 'sold',
        images: [
            'cars/soldcars/picaso.jpg'],
    },
           {
        id: 'Seat-Ibiza-2016',
        title: 'Seat Ibiza Vista Sport',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/ibiza.webp' ],
    }, 
       {
        id: 'Peugeot-2008-2017',
        title: 'Peugeot 2008 Active',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/2008.jpg' ],
    }, 
    {
        id: 'ford-fiesta-2014',
        title: 'Ford Fiesta Zetec',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/fiestablue.webp' ],
    },
    {
        id: 'peugeot-2008-2017',
        title: 'Peugeot 2008 Allure',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/peugot.webp' ],
    },
    {
        id: 'vauxhall-vivaro-2020',
        title: 'Vauxhall Vivaro 2700 Dynamic S/S',
        year: 2020,
        status: 'sold',
        images: [ 'cars/soldcars/vivaro.webp' ],
    },
    {
        id: 'audi-a1-2013',
        title: 'Audi A1 Sport',
        year: 2013,
        status: 'sold',
        images: [ 'cars/soldcars/audiA1.webp' ],
    },
    {
        id: 'ford-transit-connect-2019',
        title: 'Ford Transit Connect',
        year: 2019,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransit.webp' ],
    },
    {
        id: 'honda-crv-2015',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondaCRV.webp' ],
    },
    {
        id: 'ford-transit-custom-2016-blue',
        title: 'Ford Transit Custom 290',
        year: 2016,
        status: 'sold',
        images: [ 'cars/soldcars/fordtransitblue.webp' ],
    },
    {
        id: 'ford-focus-2017',
        title: 'Ford Focus Zetec Ecoboost',
        year: 2017,
        status: 'sold',
        images: [ 'cars/soldcars/fordfocus.jpg' ],
    },
   {
        id: 'bmw-x1-2014',
        title: 'BMW X1 SE',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/bmwx1.jpg' ],
    },
    {
        id: 'ford-fiesta-2011',
        title: 'Ford Fiesta Titanium',
        year: 2011,
        status: 'sold',
        images: [ 'cars/soldcars/blackfiesta.jpg' ],
    },
    {
        id: 'honda-crv-2015-grey',
        title: 'Honda CR-V SR',
        year: 2015,
        status: 'sold',
        images: [ 'cars/soldcars/hondacrvgrey.webp' ],
    },
    {
        id: 'nissan-qashqai-2014',
        title: 'Nissan Qashqai',
        year: 2014,
        status: 'sold',
        images: [ 'cars/soldcars/nissanqas.webp' ],
    },
];
const featuredVehicleIds = ['nissan-xtrail-2016','peugeot-2008-2016','kia-ceed-2020'];